./runner ../aisopos_ntua.txt 
./runner ../debate.txt
./runner ../english_dailabor.txt
./runner ../irony.txt
./runner ../nikolaos_ted.txt
./runner ../pang_movie.txt
./runner ../sanders.txt
./runner ../sarcasm.txt
./runner ../sentistrength_bbc.txt
./runner ../sentistrength_digg.txt
./runner ../sentistrength_myspace.txt
./runner ../sentistrength_rw.txt
./runner ../sentistrength_twitter.txt
./runner ../sentistrength_youtube.txt
./runner ../stanford_tweets.txt
./runner ../tweet_semevaltest.txt
./runner ../vader_amazon.txt
./runner ../vader_movie.txt
./runner ../vader_twitter.txt
./runner ../vader_nyt.txt